### ISSUE TITLE
Add better string validation

### ISSUE THREAD

**Issue by Rolandisimo** [joanllenas/ts.data.json#10]
Cases with `JsonDecoder.string` make the key required to be a string, but sometimes the string can be an empty one e.g. `""`. Another case, would be when the value can be any string other than certain values e.g. would fail on `"STOP"`.

In my case I need to ensure empty strings for required keys fail. Is there a way to do that?

In my eyes I see 2 ways to solve this 1) an opt-in feature to fail on an empty string value in case of a required key, 2) add an optional exclude value array for strings e.g. `{ exclude: ["value1", "value2"] }`

**Comment by Rolandisimo** [comment]
I went over the code and if we choose to say that no required string key can be an empty string, it's gonna be enough to simply add a check whether the value is truthy e.g. `json && typeof json === "string"`

**Comment by joanllenas** [comment]
Hi @Rolandisimo ,
you can create your own decoders and run them with `JsonDecoder.allOf()`.
Check this out: https://stackblitz.com/edit/typescript-uze2bj

Cheers!

**Comment by Rolandisimo** [comment]
Great stuff, thanks

**Comment by Rolandisimo** [comment]
@joanllenas would be great to add this custom decoder approach to the docs

**Comment by thefliik** [comment]
https://github.com/joanllenas/ts.data.json#jsondecoderallof

**Comment by Rolandisimo** [comment]
My bad. Thanks
