### ISSUE TITLE
ts.data.json 2.0?

### ISSUE THREAD

**Issue by thefliik** [joanllenas/ts.data.json#13]
So I really like `ts.data.json`, and a while back I decided to [open an issue](https://github.com/denoland/deno_std/issues/491) in the [Deno Standard Library](https://github.com/denoland/deno_std) suggesting that they include a decoder module in deno standard. Eventually, I ended up trying my hand at a [PR](https://github.com/denoland/deno_std/pull/522). While the PR hasn't gotten much traction (I think one of the reasons for this is that Deno just isn't far enough along for the maintainers to focus on the standard library much), it did allow me to think critically about `ts.data.json`, and learn about some other, similar libraries.

For example, some of the issues I've had with `ts.data.json`:

- The requirement that you provide a `name` argument to many decoders.
- The formatting of the error messages -- I don't find the built-in format particularly useful, and often found myself re-writing the error messages.
- Difficulty customizing error messages.
- Inability for a decode function to return a promise (yes, you can pass a promise to a decoder as input, but the decode function itself can't be asynchronous).
- Inability to return all errors (if appropriate) rather than the first.

I also learned that the decoder pattern is pretty popular (I imagine you already know this), and there are a number of typescript specific libraries to choose from. For example, [io-ts](https://github.com/gcanti/io-ts) for functional programming,  or [decoders](https://github.com/nvie/decoders) which implements a pattern similar to this library. Some of the issues I've had with `ts.data.json` are addressed by these other libraries, but not all of them are. Also, the library with the best support for custom error messages I found, `io-ts`, is written in a functional style which doesn't appeal to me.

I decided to build out a new API to address these issues, and the repo can be seen here: https://gitlab.com/john.carroll.p/ts-decoders.

For me, the `ts-decoders` repo has become my `ts.data.json` 2.0. It provides a more extensible API with explicit support for customizing the error messages of decoders, is tree shakable, and has full async support. If you like the API / library, I'm open to upstreaming my work. This being said, I'm not sure updating this repo with that code makes the most sense (from a user's perspective), for a few reasons:

1. The new repo is a complete rewrite of the API (though obviously it shares many concepts). Transitioning to the new API would be no different from transitioning to a different decoder library (e.g. [decoders](https://github.com/nvie/decoders)). 
2. This repo is still a fork of `aische/JsonDecoder`, and the `ts-decoders` library is not a fork of `aische/JsonDecoder`.
3. The new API is not designed to specifically be a `json` decoders library. For example, you could create an `AsyncDecoder` to handle decoding io from a file. This makes the `ts.data.json` name a bit of a misnomer.

Instead, what I was thinking (if you are open to it) is inviting you to be a maintainer of the new library with me (if you're not interested in Gitlab, where it is currently located, I'm happy to move it to Github). FYI though, while I maintain a few open source typescript libraries ([rSchedule](https://gitlab.com/john.carroll.p/rschedule), [Angular IsLoading](https://gitlab.com/service-work/is-loading), [Angular SizeObserver](https://gitlab.com/service-work/size-observer)),  I don't have any experience working with a co-maintainer, so I imagine there will be some growing pains. Personally, that's not something I'm not worried about, but I figured I should mention it.

Anyway, if you're not interested in the new API, or if you like the current `ts.data.json` API, I'm happy to go my own way with `ts-decoders`. Regardless, thanks again for all your work maintaining this library!

PS: If you have any questions about the new API, why decisions were made, etc, I'm happy to answer them. The repo is fully tested, and there's a good start on documentation in the readme, but all the code isn't fully commented.

**Comment by thefliik** [comment]
Hmm, I just updated the CI config and I see that it broke the tests. FYI, all the tests pass on my computer, I'll have to fix the CI config later tonight.

**Comment by joanllenas** [comment]
Hey @thefliik , I forked this  repo out of necessity because there wasn't an npm package of the library and we wanted to use it in our project. Later on, a few things were added to suit our needs and to make the library a little bit more production-ready, but the essence of this library hasn't changed much.

Let me know when you release your library, which by the way looks really good at first glance, and I'll link it in the readme.
I'll give it a try tomorrow. If there's something I can contribute to I'll happily submit a PR. I'm not especially interested in being a contributor without earning the title by actually contributing though.
I really appreciate the invite anyway!

**Comment by thefliik** [comment]
> I'll give it a try tomorrow. If there's something I can contribute to I'll happily submit a PR. I'm not especially interested in being a contributor without earning the title by actually contributing though.
> I really appreciate the invite anyway!

👍 makes sense. I'll leave a comment here when I remove the "beta" tag from the repo. At the moment, there are no issues I'm aware of. The beta tag exists because it's just so new and unused in the real world.

Let me know if you have any feedback and thanks again!
