### ISSUE TITLE
How to decode discriminated union types with nested json?

### ISSUE THREAD

**Issue by svdHero** [joanllenas/ts.data.json#18]
Hi there,

I am new to front-end development and to json decoders. In my front-end TypeScript code I have the following discriminated union (DU) type:
```typescript
type FooA = {
    duKind: "FooA",
    myPropA: string
}

type FooB = {
    duKind: "FooB",
    myPropB: number
}

type Foo = FooA | FooB
```

My back-end REST API returns either
```json
{
    "foo" : {
        "fooA": {
            "myPropA": "Hello World"
        }
    }
}
```
or
```json
{
    "foo" : {
        "fooB": {
            "myPropB": 42
        }
    }
}
```
depending on the DU case.

How can I map this to my DU types using decoders?
```typescript
const fooADecoder: JsonDecoder.Decoder<FooA> = ???;
const fooBDecoder: JsonDecoder.Decoder<FooB> = ???;
const fooDecoder: JsonDecoder.Decoder<Foo> = JsonDecoder.oneOf<Foo>([
    fooADecoder,
    fooBDecoder
], "Foo");
```
I guess for the `duKind` I can use `JsonDecoder.constant`, but the main problem is that I have to reduce the "object nesting" from `"foo": { "fooA": { "myPropA": ...}}` in JSON to `{myPropA: ...}` in TypeScript.

This problem probably is not limited to DUs, but a general question of how to reduce/compress/squeeze JSON object nesting levels within a decoder.

Any help would be much appreciated, since this is a show stopper for me right now.

**Comment by joanllenas** [comment]
Hi @svdHero, 
the key to solving your problem is mapping over the decoded API payload.
Also, you need to make an intermediate step and decode the payload before transforming it to your final domain model.

Take a look at this stackblitz: https://stackblitz.com/edit/typescript-j3gfyw

**Comment by joanllenas** [comment]
Hope this helps

**Comment by svdHero** [comment]
@joanllenas Thank you so much for your help. I'll give the `map` function a try.
Maybe it could help adding `map` to the documentation? I had a look, but couldn't find it there.

**Comment by joanllenas** [comment]
@svdHero you are totally right, I should add all those functions to the docs. It's advanced usage but it's there anyway!
