### ISSUE TITLE
Support for tuples.

### ISSUE THREAD

**Issue by halogenandtoast** [joanllenas/ts.data.json#22]
It would be nice to have support for tuples: https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.3.3

**Comment by joanllenas** [comment]
Hi @halogenandtoast , that's an interesting feature to have.
I'll give it a thought.
Thanks.

**Comment by svdHero** [comment]
I was about to post the same issue. I have any array of tuples and need to write a decoder for that.
@halogenandtoast do you have an easy work-around for this problem and would you be willing to share a code snippet?

**Comment by svdHero** [comment]
For my special case, I came up with this:

```typescript
type StringPair = readonly [string,string]

function isArray(value: any): value is any[] {
    return Array.isArray(value)
}

function jsonDecoderErrorMessagePrimitive(value: any, tag: string): string {
    return `${JSON.stringify(value)} is not a valid ${tag}`
}

const stringPairDecoder: JsonDecoder.Decoder<StringPair> = new JsonDecoder.Decoder(value => {
    if(isArray(value)){
        if(value.length===2) {
            const fst = JsonDecoder.string.decode(value[0])
            if(fst.isOk()){
                const snd = JsonDecoder.string.decode(value[1])
                if(snd.isOk()){
                    return ok<StringPair>([fst.value,snd.value])
                }
            }
        }
    }
    return err<StringPair>(jsonDecoderErrorMessagePrimitive(value, "StringPair"))
})
```
I haven't bothered with a more generic and reusable workaround, yet. Any ideas?

**Comment by halogenandtoast** [comment]
My "solution" was to forgo doing any checks on the structure and just using `JsonDecoder.succeed` but at some point I may try writing a real decoder for the numerous tuples I have.

**Comment by joanllenas** [comment]
FYI this is available via onv1.5.0
https://github.com/joanllenas/ts.data.json/releases/tag/v1.5.0
