### ISSUE TITLE
FR: Decode to class instance

### ISSUE THREAD

**Issue by rhofour** [joanllenas/ts.data.json#24]
I could use something like JsonDecoder.object, but which returns a class instance rather than a plain object. You can work around this by having an interface FooData and a class Foo that implements FooData and takes FooData as the argument to the constructor, but I'd rather eliminate all that boilerplate.

I'm fairly certain it's possible to do this, but I'm not sure if it's possible to do this without type assertions.

**Comment by joanllenas** [comment]
Hi @rhofour, you can use `map` to create the class instance after decoding the json payload:

https://stackblitz.com/edit/typescript-jsondecode-class?file=index.ts
```ts
class User {
  constructor(public name: string){};
}

const userDecoder = JsonDecoder.object<User>({
  name: JsonDecoder.string
}, 'User').map(u => new User(u.name));


console.log(userDecoder.decode({name: 'Richard'}));
```

I hope this helps!
