### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by rhux** [joanllenas/ts.data.json#3]
I just found this, and it looks very interesting.  Do you have have an example of how the "hasLength" decoder would work.  I can't seem to figure it out on my own.

**Comment by thefliik** [comment]
@rhux I found it's pretty easy to create custom decoders. Just look at the source for how any of the existing decoders were created and mimic them
https://github.com/joanllenas/ts.data.json/blob/9c801af9ff0ece1deb253eb2313edea14c2bcd7f/src/json-decoder.ts#L103-L109

**Comment by joanllenas** [comment]
Take a look at this example: https://stackblitz.com/edit/typescript-97ergz
