### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by GimpMaster** [joanllenas/ts.data.json#30]
I really appreciate this project. We have used it on a number of our projects now. The typescript generics are awesome to make sure that you are matching well.

Thanks

**Comment by joanllenas** [comment]
Thanks for your kind words @GimpMaster
I'm glad that this is useful for your projects!

I've dedicated a lot of hours maintaining this library, but it's worth acknowledging that the merit also goes for [Daniel van den Eijkel](https://github.com/aische), the original author of the library  🙌

Open Source FTW!
