### ISSUE TITLE
How would you decode an empty object

### ISSUE THREAD

**Issue by GimpMaster** [joanllenas/ts.data.json#34]
I use ts.data.json to decode incoming api req.body. I have one endpoint that I expect that no parameters should be passed in. the express body parser returns an empty object. I would ideally like to verify its an empty object.

When I try.

`JsonDecoder.isExactly({})`

I get an error `{} is not {}`

which makes sense because they are different objects.

so I tried.

JsonDecoder.objectStrict<{}>({}, 'GET /');

which lets everything pass.

Just curious what you would suggest. 

Thanks!

**Comment by joanllenas** [comment]
Hey @GimpMaster ,
you may have come across an unsupported scenario.
I'll take a look during the weekend.

Thanks for reporting!

**Comment by joanllenas** [comment]
@GimpMaster There's a new decoder for empty objects: https://github.com/joanllenas/ts.data.json/releases/tag/v2.2.0

**Comment by GimpMaster** [comment]
@joanllenas - Thank you!
