### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by nateabele** [joanllenas/ts.data.json#4]
Hey! Just adopted this library for a big project at work. Thanks for putting it together (or at least, thanks for sprucing up the thing you forked it from).

There are a few things that I think would make this a lot more usable. If you're interested, I'd be happy to submit some PRs:

 - Implementing the [Fantasy Land Spec](https://github.com/fantasyland/fantasy-land) (mainly just `.ap()` and `.map()`) on `Ok` and `Err`
 - Using property accessors to auto-bind `.decode()` and `.decodeThen()` to make them easier to use in point-free compositions
 - Exposing additional metadata in `Err` to allow more flexible handling, i.e. building validation, etc.

Let me know what you think! Thanks again.

**Comment by thefliik** [comment]
Just another two cents: as another consumer of this library, I am wary about seeing its size increase. I'm not familiar with the Fantasy Land Spec and, perhaps it's my lack of familiarity with algebraic math (or my lack of familiarity with functional programming), but the link doesn't do much to explain why adding `.ap()` and `.map()` methods to `Ok` and `Err` would be generally useful.

@nateabele Could you add in some info on why these updates are useful? I imagine for the last bullet you simply mean adding some sort of customizable `.data` property to the `Err` object?

Another (breaking) change I've been musing over proposing is removing the `JsonDecoder` namespace. The namespace prevents tools like rollup from being able to tree shake this library.

**Comment by nateabele** [comment]
Hey, thanks for the quick response.

> Just another two cents: as another consumer of this library, I am wary about seeing its size increase. I'm not familiar with the Fantasy Land Spec and, perhaps it's my lack of familiarity with algebraic math (or my lack of familiarity with functional programming), but the link doesn't do much to explain why adding `.ap()` and `.map()` methods to `Ok` and `Err` would be generally useful.

Totally understood. Consider this example. I'm taking in some configuration that I use to make a request for an OAuth token, and that data comes from an outside source (env vars) that may or may not be present:

```typescript
/**
 * The setup: my type def and decoder
 */
export type Config = {
  url: string;
  clientId: string;
  clientSecret: string;
  username: string;
  password: string;
};

export const decodeConfig = JsonDecoder.object<Config>({
  url: JsonDecoder.string,
  clientId: JsonDecoder.string,
  clientSecret: JsonDecoder.string,
  username: JsonDecoder.string,
  password: JsonDecoder.string,
}, 'Config');
```

```typescript
/**
 * The call to generate the HTTP request to get the token
 */
toToken({
  clientId: '...',
  clientSecret: '...',
  username: '...',
  password: '...',
}); // => Ok(new Post({ url: ..., body: ... })) | Err<whatever>
```

Here's the code I _want_ to write:

```typescript
const toToken = pipe(
  decodeConfig.decode,
  map(pipe(Mappers.toTokenRequest, HttpUtils.withFormEncoding, construct(Post)))
);
```

It's a simple composition of functions with a left-to-right flow, using helpers from the [Ramda](https://ramdajs.com) library (I see you have some Elm repos in your profile—`pipe()` is equivalent to `>>`). I can pass it an unknown config object and get back a type-safe `POST` request, from which I can generate a [`Future`](https://github.com/fluture-js/Fluture) for the actual request.

Because `decode()` isn't bound, and because `Result` types don't support any composition, it gets uglier:

```typescript
const toToken = (config) => {
  const decoded = decodeConfig.decode(config);

  return (decoded instanceof Ok)
    ? new Post(HttpUtils.withFormEncoding(Mappers.toTokenRequest(decoded.value)))
    : decoded
};
```

> I imagine for the last bullet you simply mean adding some sort of customizable .data property to the Err object? (which does seem useful--and obviously has a negligible impact on size)

Yeah exactly. Just being able to have direct access to the raw data that the error message is generated from.

> Another (breaking) change I've been musing over proposing is removing the JsonDecoder namespace and instead exporting the decoders individually. The namespace prevents tools like rollup from being able to tree shake this library.

Yeah that makes sense. If you want the namespace, you can always do `import * as JsonDecoder`, so it's a pretty simple migration path.

Btw, for some additional background on Fantasy Land, if you're interested in doing FP in JS, check out this blog post: http://james-forbes.com/#!/posts/the-perfect-api

**Comment by joanllenas** [comment]
Hi @nateabele , 
thanks for your suggestions, they all sound legit to me.
The library was very focused on solving the decoding story, so the Result type was almost just an implementation detail. I'm ok with giving it a little more protagonism to be able to make it more composable and, regarding @thefliik concerns, these additions won't add much overhead, right?
If you have something in mind already please, feel free to submit a PR!

**Comment by nateabele** [comment]
> these additions won't add much overhead, right?

Yeah, not at all. Basically just:
```typescript
Ok {
  map(fn) { return ok(fn(this.value)); }
}
```
And:
```typescript
Err {
  map(fn) { return this; }
}
```

Plus, if you add auto-binding and drop in a couple other things like `reduce`, you can throw away `decodePromise()`, and you get composability with other functional data structures for free.

**Comment by thefliik** [comment]
@nateabele gotcha, thanks for the explanation! 👍

**Comment by nateabele** [comment]
@thefliik You bet!

Here's a li'l quick one for the `map()` stuff: https://github.com/joanllenas/ts.data.json/pull/5

**Comment by joanllenas** [comment]
@nateabele I added a few tests for the `Result` type and detected a couple of minor issues with the functor interface types, but it's fixed now.
Let me know if you find any issues.

Thanks for your contribution!

**Comment by nateabele** [comment]
Nice! Yeah, looks great. Thanks!
