### ISSUE TITLE
Not working with Artifactory because of unfortunate name

### ISSUE THREAD

**Issue by venil7** [joanllenas/ts.data.json#7]
Hello, 
this is a great library and I want to use it in a major organization - however all our `npm install`'s are proxied through a corporate Artifactory instance. 
This library has an unconventional for an npm packgae name with dots and not dashes (`ts-data-json` 🤔 ) which prevents Artifactory from letting me install it, as it thinks I'm trying to install a `*.json` file.

any chance this can be renamed to a more conventional dash-separated notation?

**Comment by joanllenas** [comment]
Hi @venil7 , this package name conforms to the npm naming rules, so the problem resides on how Artifactory handles npm packages.
I suggest that you open an issue on  their issue tracker.
Cheers

**Comment by thccorni** [comment]
@venil7 I have the same issue, could you resolve it somehow?
