### ISSUE TITLE
Optionally fail object decoder when encountering unknown keys

### ISSUE THREAD

**Issue by Dremora** [joanllenas/ts.data.json#8]
My use case: I have 1600 JSON files with complex structure that I want to type. The way I want to approach this is by iteratively running the decoder, inspecting the first error message and extending the decoder. I don't know in advance which fields those JSON files have, I want the decoder to help me in finding this out. I thus want the decoder to fail whenever it encounters an unknown object key.

Similar option exists in [tcomb-validation](https://github.com/gcanti/tcomb-validation) is called [strict](https://github.com/gcanti/tcomb-validation#basic-usage).

**Comment by joanllenas** [comment]
Hi @Dremora ,
sounds like a nice feature to add, it could be useful to others.
Let me think about it and during the next few days, I'll try to implement it.
Cheers!

**Comment by fabb** [comment]
Yes that would be a nice feature.

Awesome library by the way!

**Comment by joanllenas** [comment]
Closed via https://github.com/joanllenas/ts.data.json/pull/9
For some reason, standard-version did not create a minor release, just a patch release (0.2.1).

Anyway, let me know if there are any issues.
Cheers!
